# Introduction to Deep Learning with PyTorch
## Tensors in Pytorch

This tutorial gives a basic introduction to [PyTorch](http://pytorch.org/), a deep learning framework deveploped by Facebook AI Research (FAIR). Pytorch uses Tensors instead of the Numpy arrays which can easily be moved to GPUs for fast training in deep Neural Networks. 


## Tensors

In [25]:
import torch
import numpy as np
# A numpy array of zeros
x = np.zeros((4,3))
print("Numpy Array")
print(x)



Numpy Array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


 In a similar way we can create a torch array as follows

In [17]:

print("Torch Tensor")
y = torch.zeros(5,3)
print(y)

Torch Tensor
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


A random torch tensor can be created as 

In [58]:

tensor_r = torch.rand(5,6)
print(tensor_r)

tensor([[0.0830, 0.7932, 0.3187, 0.0404, 0.6001, 0.8693],
        [0.4495, 0.9380, 0.0450, 0.5819, 0.2952, 0.5434],
        [0.1237, 0.3424, 0.5582, 0.0219, 0.4490, 0.0623],
        [0.2935, 0.9791, 0.0996, 0.6220, 0.3688, 0.4552],
        [0.0588, 0.9088, 0.2955, 0.2313, 0.8230, 0.1191]])


Conversion of Numpy Array to Tensor and back!!!

In [73]:

a = np.ones((5,4))
tensor_a = torch.from_numpy(a)
print("Tensor from Numpy Array")
print(tensor_a)



Tensor from Numpy Array
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [72]:
numpy_a = tensor_a.numpy()

print("Numpy array from Torch Tensor")
print(numpy_a)

Numpy array from Torch Tensor
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


An important point to keep in consideration is that numpy array and Tensor share memory, so if I change numpy array the torch tensor will also change,


In [75]:
torch.tan_(tensor_a)

tensor([[1.5574, 1.5574, 1.5574, 1.5574],
        [1.5574, 1.5574, 1.5574, 1.5574],
        [1.5574, 1.5574, 1.5574, 1.5574],
        [1.5574, 1.5574, 1.5574, 1.5574],
        [1.5574, 1.5574, 1.5574, 1.5574]], dtype=torch.float64)

In [78]:
a

array([[1.55740772, 1.55740772, 1.55740772, 1.55740772],
       [1.55740772, 1.55740772, 1.55740772, 1.55740772],
       [1.55740772, 1.55740772, 1.55740772, 1.55740772],
       [1.55740772, 1.55740772, 1.55740772, 1.55740772],
       [1.55740772, 1.55740772, 1.55740772, 1.55740772]])

Note: Here, a and tensor_a are sharing the same memory.

 A new tensor can be created based on the properties of the existing tensor( i.e. th same shape and data type of the existing tensor), unless explicitly specified

In [60]:
new_tensor = torch.rand_like(tensor_r, dtype= torch.float64)
print(new_tensor)

tensor([[0.8724, 0.6146, 0.7633, 0.3997, 0.8763, 0.4190],
        [0.4628, 0.3883, 0.1589, 0.0023, 0.2522, 0.3508],
        [0.9283, 0.8029, 0.3650, 0.1828, 0.1719, 0.7535],
        [0.3464, 0.2966, 0.9455, 0.1520, 0.3840, 0.3658],
        [0.8482, 0.8694, 0.7713, 0.4805, 0.7574, 0.7370]],
       dtype=torch.float64)


To get the size of the tensor,

In [45]:
new_tensor.size()

torch.Size([5, 5])

An operation on torch such as torch.copy_(), torch.tan_(), etc will change the value of the tensor in memory.

In [55]:
x= torch.tensor(30, dtype=torch.float64)
print(x)
torch.tan_(x)
print(x)

tensor(-6.4053, dtype=torch.float64)

Note: The value of tensor is not same after torch.tan_() operation

A new torch tensor can be reshaped into another shape as,

In [63]:
# Considering new_tensor
 tensor_v = new_tensor.view(-1,3)

The dimension if -1 will automatically inferred from other dimensions, in this case 10.  

In [64]:
tensor_v

tensor([[0.8724, 0.6146, 0.7633],
        [0.3997, 0.8763, 0.4190],
        [0.4628, 0.3883, 0.1589],
        [0.0023, 0.2522, 0.3508],
        [0.9283, 0.8029, 0.3650],
        [0.1828, 0.1719, 0.7535],
        [0.3464, 0.2966, 0.9455],
        [0.1520, 0.3840, 0.3658],
        [0.8482, 0.8694, 0.7713],
        [0.4805, 0.7574, 0.7370]], dtype=torch.float64)

### Note:
To reshape a Torch tensor we can also use reshape() and resize_() functions. The function resize_() is a kind of inplace function which will replace the value of Torch tensor in the memory, without making a copy.

A very important function that we will be requiring in the further lessons, is the matrix multiplication required for computing the outputs in the neural networks.


In [ ]:
torch.manual_seed(3)
features = torch.randn((1, 5))
# True weights for our data
weights = torch.randn_like(features)

out = torch.matmul(features,weights)

You might have got an error due to size mismatch stating,
### RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at /opt/conda/condabld/pytorch_1533672544752/work/aten/src/TH/generic/THTensorMath.cpp:2070

Can you use the view(), or resize() function to get the correct output?
If everything works out perfectly you will get your output as 
### out= tensor([[1.4382]]) 

,or you can just call out.item() to get the tensor value.

### out = 1.43820


Moving the Tensor to Cuda!! To check if you are working on gpu devie,

In [79]:
torch.cuda.is_available()

True

In [81]:
tensor_q= torch.rand(5,4)
tensor_q = tensor_q.cuda()

In [82]:
tensor_q

tensor([[0.8639, 0.7967, 0.6456, 0.1351],
        [0.6018, 0.7803, 0.7927, 0.2867],
        [0.1770, 0.3268, 0.6489, 0.6362],
        [0.5011, 0.0461, 0.7126, 0.1449],
        [0.5392, 0.5188, 0.0305, 0.2849]], device='cuda:0')